apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "consul-backup-gcs.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "consul-backup-gcs.name" . }}
    helm.sh/chart: {{ include "consul-backup-gcs.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    {{- with .Values.labels.configMap }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- if .Values.annotations.configMap }}
  annotations:
    {{- with .Values.annotations.configMap }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
data:
  vars.yml: |
    consul_environment:
      CONSUL_HTTP_ADDR: {{ .Values.consul.address }}
    gcs_bucket: {{ required "GCS bucket is required" .Values.gcs.bucket }}
    gcs_prefix: {{ .Values.gcs.prefix }}
    {{- if .Values.gcs.serviceAccountKey }}
    service_account_key: /gcs/gcs.json
    {{- end }}
