apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ include "consul-backup-gcs.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "consul-backup-gcs.name" . }}
    helm.sh/chart: {{ include "consul-backup-gcs.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    {{- with .Values.labels.cronJob }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- if .Values.annotations.cronJob }}
  annotations:
    {{- with .Values.annotations.cronJob }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  schedule: {{ .Values.schedule }}
  concurrencyPolicy: {{ .Values.concurrencyPolicy }}
  successfulJobsHistoryLimit: {{ .Values.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.failedJobsHistoryLimit }}
  jobTemplate:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "consul-backup-gcs.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        {{- with .Values.labels.cronJob }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- with .Values.annotations.cronJob }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      completions: 1
      parallelism: 1
      {{- if .Values.ttlSecondsAfterFinished }}
      ttlSecondsAfterFinished: {{ .Values.ttlSecondsAfterFinished }}
      {{- end }}
      template:
        metadata:
          labels:
            app.kubernetes.io/name: {{ include "consul-backup-gcs.name" . }}
            app.kubernetes.io/instance: {{ .Release.Name }}
            {{- with .Values.labels.pods }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          annotations:
            {{- with .Values.annotations.pods }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
        spec:
          serviceAccountName: {{ .Values.serviceAccount }}
          automountServiceAccountToken: true
          restartPolicy: OnFailure
          containers:
            - name: {{ .Chart.Name }}
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              resources:
                {{- toYaml .Values.resources.backup | nindent 16 }}
              volumeMounts:
                - name: config
                  mountPath: /config
                  readOnly: true
                {{- if .Values.gcs.serviceAccountKey }}
                - name: gcs
                  mountPath: /gcs
                  readOnly: true
                {{- end }}
              {{- with .Values.env }}
              env:
                {{- toYaml . | nindent 16 }}
              {{- end }}
              {{- with .Values.args }}
              args:
                {{- toYaml . | nindent 16 }}
              {{- end }}
          volumes:
            - name: config
              configMap:
                name: {{ include "consul-backup-gcs.fullname" . }}
            {{- if .Values.gcs.serviceAccountKey }}
            - name: gcs
              secret:
                name: {{ include "consul-backup-gcs.fullname" . }}
            {{- end }}
          {{- with .Values.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.affinity }}
            affinity:
              {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.tolerations }}
            tolerations:
              {{- toYaml . | nindent 12 }}
          {{- end }}
