{{- if .Values.gcs.serviceAccountKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "consul-backup-gcs.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "consul-backup-gcs.name" . }}
    helm.sh/chart: {{ include "consul-backup-gcs.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    {{- with .Values.labels.secret }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- if .Values.annotations.secret }}
  annotations:
    {{- with .Values.annotations.secret }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
data:
  gcs.json: {{ .Values.gcs.serviceAccountKey | b64enc }}
{{- end }}
