# See https://kubernetes.io/docs/tasks/job/automated-tasks-with-cron-jobs/#schedule
schedule: "0 3 * * *"
# See https://kubernetes.io/docs/tasks/job/automated-tasks-with-cron-jobs/#concurrency-policy
concurrencyPolicy: "Allow"

successfulJobsHistoryLimit: "10"
failedJobsHistoryLimit: "10"

ttlSecondsAfterFinished: 86400

image:
  repository: basisai/consul-backup-gcs
  tag: 0.3.3
  pullPolicy: IfNotPresent

env: []

nameOverride: ""
fullnameOverride: ""

serviceAccount: "consul-backup-gcs"

consul:
  # Consul Server address and port
  # Remember to update port for TLS
  address: consul-server.service.consul:8500
  tls:
    enabled: false
    cacert: null

resources:
  backup:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

labels:
  serviceAccount: {}
  cronJob: {}
  pods: {}
  configMap: {}
  secret: {}

annotations:
  serviceAccount: {}
  cronJob: {}
  pods: {}
  configMap: {}
  secret: {}

gcs:
  bucket: ""
  prefix: "backup/consul/"
  serviceAccountKey: null
